version: '3.8'

services:
  opti_api_starter_postgres: # Needs updating
    image: postgres:alpine
    container_name: opti_api_starter_postgres # Needs updating
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - opti_api_starter_postgres_data:/var/lib/postgresql/data # Needs updating

  opti_api_starter_redis: # Needs updating
    image: redis:alpine
    container_name: opti_api_starter_redis # Needs updating
    ports:
      - '6379:6379'
    volumes:
      - opti_api_starter_redis_data:/data # Needs updating

networks:
  default:
    name: opti_api_starter # Needs updating

volumes:
  opti_api_starter_postgres_data: # Needs updating
  opti_api_starter_redis_data: # Needs updating