version: '3.8'

services:
  opti_api_postgres_test:
    image: postgres:alpine
    container_name: opti_api_test_postgres
    restart: 'no'
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432' # Different port to avoid conflict with the development environment
    volumes:
      - opti_api_postgres_test:/var/lib/postgresql/data

  opti_api_redis_test:
    image: redis:alpine
    container_name: opti_api_test_redis
    ports:
      - '6380:6379' # Different port to avoid conflict with the development environment
    volumes:
      - opti_api_redis_test:/data

networks:
  default:
    name: opti_api_starter_test

volumes:
  opti_api_postgres_test:
  opti_api_redis_test:
